#!/usr/bin/env python
import json
import os
from subprocess import Popen
import subprocess
import signal
import click


@click.group()
def cli():
    pass

@cli.group()
def env():
    pass


@env.command()
@click.argument('name')
def create(name):
    data = {
        'namespace': name,
            }
    out = subprocess.check_output(["kubeless", "function", "call", "boot", "--data", json.dumps(data)])
    click.echo(out)


@env.command()
@click.argument('name')
def delete(name):
    out = subprocess.check_output(["kubectl", "delete", "ns", "kubeflow-" + name])
    click.echo(out)


@env.command()
def list():
    out = subprocess.check_output(["kubectl", "get", "ns"])
    click.echo(b"".join([l.split(b" ")[0].split(b"-")[1] for l in out.split(b"\n") if b'kubeflow' in l]))

@env.command()
@click.argument('name')
def use(name):
    if not os.path.exists(os.getenv("HOME")+"/.kubeflow/"):
        os.makedirs(os.getenv("HOME") + "/.kubeflow/")
    with open(os.getenv("HOME") + "/.kubeflow/env", "w") as f:
        f.write(name)
    click.echo("Using environment " + name)

@cli.command()
def jupyter():
    with open(os.getenv("HOME") + "/.kubeflow/env", "r") as f:
        env = f.read()
    p = Popen(['kubectl', 'port-forward', '-n', 'kubeflow-' + env, 'svc/tf-hub-lb', '8990:80'])
    click.echo("Listening on 192.168.0.106:8989")
    signal.signal(signal.SIGINT, lambda sig, frame: p.terminate())
    signal.pause()




if __name__ == '__main__':
    cli()
