#!/bin/bash
KF=github.com/kkasravi/kf/kf
KFROOT=$(dirname $GOPATH/src/$KF)
rm -rf $GOPATH/src/$KF $KFROOT/functions/* cmd
mkdir $GOPATH/src/$KF

remove()
{
  for i in $(kubeless function ls |grep -v '^NAME'|awk '{print $1}');do
    kubeless function delete $i
  done
  sleep 5
}

add()
{
  local name=$1 functionpath=$2 parent templatefile=../templates/python/template.py
  if [[ $# == 3 ]]; then
    parent=$3
    cobra add $1 -p ${parent}Cmd
  else 
    cobra add $1
  fi
  mkdir $functionpath
  file=$functionpath/${1}.py
  cp $templatefile $file
  cd $functionpath
  kubeless function deploy $1 --from-file ${1}.py --handler ${1}.handler --runtime python3.6
  cd -
}

remove
cobra init $KF
cd $GOPATH/src/$KF
for i in create delete remove run status use whoami command;do
  add $i ../functions/$i
done
for i in list health info; do
  add $i ../functions/status/$i status
done
ed -s main.go <<EOF
%s/kf\/kf\//kf\//
w
q
EOF
for i in $(ls cmd/*.go);do
  grep rootCmd $i >/dev/null
  if [[ $? == 0 ]]; then
    ed -s $i <<EOF1
%s/rootCmd/RootCmd/g
w
q
EOF1
  fi
done

cd $KFROOT 
mv $GOPATH/src/$KF/* .
rm -rf $GOPATH/src/$KF
