#!/bin/bash
KF=github.com/kkasravi/kf

rm -rf $GOPATH/src/$KF/*
cobra init $KF
cd $GOPATH/src/$KF
cobra add create
cobra add delete
cobra add exec
cobra add logs
cobra add remove
cobra add shell
cobra add use
cobra add whoami
cobra add user
cobra add add -p 'userCmd' 
cobra add rm -p 'userCmd' 
cobra add list -p 'userCmd'
cobra add import
cobra add pkg -p 'importCmd'
cobra add command -p 'importCmd'
